### ISSUE TITLE
Connecting RF Reciever to LPC2148 & developing code and testing it

### ISSUE THREAD

**Issue by mikeshams** [stephybaby199/Capstone-project-summer2020#4]

**Comment by mikeshams** [comment]
1. What issues did you face or others might face when connecting RF Receiver to an LPC 2148?

**Comment by kaurjas123** [comment]
Connecting LPC 2148 with  NRF24L01  was not that much tough in terms of hardware because the datasheet which I referred was updated one and all the pins and registers were clearly explained . I faced my difficulties in the software part specially when it comes about presenting my software part without getting output on hardware as my task was to present only tramsmitter side.  So, the main task was designing the loop for checking the successful transmission. Secondly deciding and observing about the transmitter or reciever side and selecting the channel accordingly.
