### ISSUE TITLE
Connection Of PIR Sensor to RF receiver and it’s coding

### ISSUE THREAD

**Issue by mikeshams** [stephybaby199/Capstone-project-summer2020#5]

**Comment by mikeshams** [comment]
1. why did you decide to use an Arduino as an interface?

**Comment by Dixa2405** [comment]
firstly we want to make our PIR sensor wireless to make our system more advance so that we need to connect the PIR sensor with any MCU which is small in size and easy to interface so we can fit it to any place to secure that area. 
its open-source platform through which its easy to use hardware and software.
this microcontroller has a lot of libraries support for different devices which make it easy to build code
its also cheap in price compared to other MCU
