### ISSUE TITLE
Interfacing & coding of LCD  and LPC 2148

### ISSUE THREAD

**Issue by mikeshams** [stephybaby199/Capstone-project-summer2020#6]

**Comment by mikeshams** [comment]
Please remove the issue ASAP!

**Comment by mikeshams** [comment]
1. What issues did you or others might face with connection of a LCD Display with the LPC2148 in terms of Hardware and Software? How to solve them?

**Comment by kaurjas123** [comment]
First issue that was faced by us during software part was that when we were compling program it was showing that target cannot be build because of large file size. After exploring this error on internet, we found that we were using student evalution version which hurdle the program to be compiled. So, we bought the key for the keil software and were able to run our code successfully.
Secondly, we faced the hardware problem that our GLCD is getting power supply but not displaying the welcome message. We are working our best to resolve this issue as we checked the interfacing of GLCD with arduino nano but didn't work. We spent one day more on this issue if not fixed we will order new GLCD.
To overcome this issue, we used LCD 16*2 and are able to display the welcome message on the LCD with the same code.We were facing display issue in this also but able to resolve by adjusting the contrast by connecting 10k potentiometer to 5V.
