### ISSUE TITLE
Interfacing ESP 32-CAM and LPC2148

### ISSUE THREAD

**Issue by mikeshams** [stephybaby199/Capstone-project-summer2020#7]

**Comment by mikeshams** [comment]
1. What issues did you or others might face with connection of an ESP 32 CAM to the LPC 2148 in terms of Hardware and software?
2. How do you solve them?

**Comment by kaurjas123** [comment]
Firstly, I tried flashing code on ESP 32- CAM with arduino nano. The problem we were facing was not able to connect with our wifi. It was showing error like wifi connection failed. Then we tried with the FTDI to TTL cable. then the connection to wifi was successful by poping message that wifi successfully connected and then I was able to flash the code by holding flash button and pressing reset button and then releasing flash button at the end. these two buttons are on the ESP 32- CAM only.
 
When mounting LPC 2148 code , in my presentation also I faced this problem the I was not getting anything on serial monitor for checking successful connection. The problem was the wrong path. So, one has to be very careful about selecting the path while flashing the bin file.
