### ISSUE TITLE
Communicating Buzzer with LPC 2148

### ISSUE THREAD

**Issue by mikeshams** [stephybaby199/Capstone-project-summer2020#9]

**Comment by mikeshams** [comment]
1. What issues did you or others might face when connecting the LPC to the buzzer?
2. How did you resolve them?

**Comment by Dixa2405** [comment]
the buzzer was already mounted on graphic controller board of LCD so we didn't face many issues but the only thing which is really needed to know soldering connection should be proper otherwise, buzzer won't work properly  and we can face delay for buzzer sound
solution for overcoming this issue is the proper connection with LPC2148 and GLCD
